---
- name: reboot system
  reboot:
    reboot_timeout: 300
    post_reboot_delay: 30
    test_command: uptime

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    enabled: yes
