---
- name: Install Kubernetes Cluster
  hosts: kubernetes_cluster
  become: yes
  gather_facts: yes

  pre_tasks:
    - name: Load credentials
      include_vars: credentials.json

  tasks:
    - name: Run full cluster installation
      include: ../site.yml
      tags: install
