---



- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true




- name: Install containerd
  ansible.builtin.apt:
    name: containerd.io
    state: present


- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'


- name: Generate default containerd config
  ansible.builtin.command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml


- name: Set SystemdCgroup = true in config.toml
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup = false'
    replace: '            SystemdCgroup = true'


- name: Restart and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
