---




- name: Install required packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository (for containerd)
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true





- name: Install latest containerd.io
  ansible.builtin.apt:
    name: containerd.io
    state: latest


- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0755'


- name: Generate default containerd config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml


- name: Set SystemdCgroup = true in config.toml
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^\s*SystemdCgroup = false'
    replace: '            SystemdCgroup = true'

- name: Remove CRI from disabled_plugins
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins = \["cri"\]'
    replace: 'disabled_plugins = []'

- name: Restart and enable containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: true
    daemon_reload: true
